### PR TITLE
Cmake upgrade and rippled 1.7 fixes

### PR DESCRIPTION
**Pull request by biddisco**
A couple of updates to the demo that allow it to work with the latest rippled and some cmake improvements.

### CODE REVIEW

**Comment by ximinez** [comment]
Hi! Thank you for your contribution and taking on the effort to bring this project more up to date. It's definitely been neglected. Part of the reason is that the "xrpl_core" module more-or-less replaces this project.

You can see an example of that replacement in a formerly-dependent project in the changeset https://github.com/ripple/validator-keys-tool/commit/bb532eb810193c8164527738e3350810f87ef912 in the "validator-keys-tool" project, which bears a lot of similarity, but went about it slightly differently. That project has also more recently been updated so that CI works consistently.

**Comment by biddisco** [comment]
That's great. I'll switch over to the other project - I just tried building it and made one small fix. If this project has been discontinued, then it might be an idea to update the project description and/or delete this one.

**Comment by biddisco** [comment]
The other project has all the FetchContent stuff working, and has the right travis setup. Closing this as it's obolete.

**Comment by ximinez** [comment]
It hasn't been discontinued so much as neglected, but thank you!

**Pull request closed without merging**
